# Generated by Django 5.2.1 on 2025-05-19 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lost', 'Потерянная вещь'), ('found', 'Найденная вещь')], max_length=10, verbose_name='Тип объявления')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('color', models.CharField(choices=[('red', 'Красный'), ('orange', 'Оранжевый'), ('yellow', 'Желтый'), ('green', 'Зеленый'), ('blue', 'Синий'), ('purple', 'Фиолетовый'), ('pink', 'Розовый'), ('brown', 'Коричневый'), ('black', 'Черный'), ('white', 'Белый'), ('gray', 'Серый'), ('gold', 'Золотой'), ('silver', 'Серебряный'), ('beige', 'Бежевый'), ('navy', 'Темно-синий'), ('teal', 'Бирюзовый'), ('olive', 'Оливковый'), ('maroon', 'Бордовый'), ('lime', 'Лаймовый'), ('aqua', 'Аквамарин'), ('coral', 'Коралловый'), ('magenta', 'Пурпурный'), ('cyan', 'Голубой'), ('lavender', 'Лавандовый'), ('salmon', 'Лососевый'), ('tan', 'Загар'), ('khaki', 'Хаки'), ('indigo', 'Индиго'), ('turquoise', 'Бирюзовый'), ('violet', 'Фиалковый'), ('crimson', 'Малиновый'), ('plum', 'Сливовый'), ('chocolate', 'Шоколадный'), ('charcoal', 'Угольный'), ('cream', 'Кремовый'), ('mint', 'Мятный'), ('emerald', 'Изумрудный'), ('ruby', 'Рубиновый'), ('sapphire', 'Сапфировый'), ('amber', 'Янтарный')], max_length=20, verbose_name='Цвет')),
                ('date_event', models.DateField(verbose_name='Дата потери/находки')),
                ('location_event', models.CharField(max_length=255, verbose_name='Место потери/находки')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='active', max_length=10, verbose_name='Статус')),
                ('reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вознаграждение')),
                ('storage_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место хранения')),
                ('hidden_details', models.TextField(blank=True, null=True, verbose_name='Скрытые детали для верификации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('images', models.ManyToManyField(blank=True, related_name='items', to='images.image', verbose_name='Изображения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='items.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
