# Generated by Django 5.2.1 on 2025-05-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_item_user_id'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE items_item ADD COLUMN user_id uuid REFERENCES users_user(id) ON DELETE CASCADE;",
            reverse_sql="ALTER TABLE items_item DROP COLUMN user_id;"
        ),
    ]
