# Generated by Django 5.2.1 on 2025-05-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_active_user_is_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPassword',
        ),
    ]
